### ISSUE TITLE
Branch name missing from sourcehut urls

### ISSUE THREAD

**Issue by josephmturner** [grtcdr/forgecast#5]
Hi Aziz! Nice work!! The manual website looks slick, and I like the package name change.

I just updated from an old commit to the latest main branch, and I noticed that urls which liaison generates for my sourcehut repo are missing the branch name. 

For example, I'm getting
`https://git.sr.ht/~breatheoutbreathein/ushin.org/log//item/build-site.el`
when I expect
`https://git.sr.ht/~breatheoutbreathein/ushin.org/log/master/item/build-site.el`

Thank for this project!

**Comment by grtcdr** [comment]
Hey Joseph,

It's nice to hear from you again, thanks for the kind words!

I'll investigate this issue and keep you up to speed :)

**Comment by grtcdr** [comment]
Does https://github.com/grtcdr/liaison/commit/4756b80ae6df6270261c98e1d4ae9ca3161293f1 solve this issue?

I tested this in a submodule setting and it fails, but that's always been the case, a long standing issue I haven't been able to address yet. However, it does return the correct branch name in a SourceHut repository.

**Comment by josephmturner** [comment]
Yes, it works now! Thanks for fixing it so quickly!!

**Comment by grtcdr** [comment]
Good to hear, you're very welcome! :)
